### ISSUE TITLE
[BUG] Question state is shared between all users

### ISSUE THREAD

**Issue by aminbenarieb** [it-muslim/arabic-verbs-telegram-bot#13]
`storage` variable was assumed to be unique for each user when he starts quiz, but eventually it happens to be shared across all of them. Needed to be fixed.

**Comment by Jihadik** [comment]
The easier solution would be to convert the `storage` to a dictionary and store everything per `chatID`. Something like
```js
storage.chatID.whatever = 10
```
should work.
