### ISSUE TITLE
Реализовать функцию выбора случайного слова и случайных вариантов

### ISSUE THREAD

**Issue by aminbenarieb** [it-muslim/arabic-verbs-telegram-bot#2]
Задача разбивается на несколько составляющих:
1. Подобрать `data storage` решение, например какую-нить обертку над `sqlite`
2. Сконвертировать данные из [spreadsheet](https://docs.google.com/spreadsheets/d/1CXdShf4dmojMtR1lML4RQrmvehcy5SRKbD9uf03qb6o/edit#gid=0) в файл для выбранного `data storage`
3. Реализовать функцию:

В файле `index.js`,  в каллбеке на команду `/play` мы должны получать `dictionary`, состоящий из:
1. выбранного рандомной формы слова из `data storage` 
2. массива 3 случайных формы из `data storage`, для выбранного выше слова + сама выбранная выше форма слова

`dictionary` выглядит примерно так:
```
 {
    "rightWord": word, // случайно выбранная форма слово, правильный вариант
    "words": words // массив вариантов форм слова: 3 из них случайные, одно выбранное ранее
  }
```

Мок функции:
```
function randomWordInfo() {
  // const word = getting random data from data storage
  // const words = get 3 random data from database that are not equal to wordId from `data storage`

  const words = [{ "ar" : "قالت"},  //TODO: Delete mock
               { "ar" : "قالوا"},
               { "ar" : "قالو"}];
  const word = { "ar" : "قالتا", "ru" : "сказали" }; //TODO: Delete mock
  words.push(word)

  return {
    "rightWord": word,
    "words": words
  }
}
```

**Comment by Jihadik** [comment]
It was solved in one of the PRs.
