### ISSUE TITLE
Rename the bot from @ArabicVerbConjugatorBot to @arabic_verbs_bot

### ISSUE THREAD

**Issue by Imangazaliev** [it-muslim/arabic-verbs-telegram-bot#26]
I think it's better to rename the bot to `@arabic_verbs_bot`, because it's easier to remember and pronounce.

**Comment by Jihadik** [comment]
I would even call it @learn_arabic_bot in order to remind ourselves, that it's not just about verbs :)

**Comment by Jihadik** [comment]
The issue is done.
