### ISSUE TITLE
Добавить приветствие

### ISSUE THREAD

**Issue by ansaril3** [it-muslim/arabic-verbs-telegram-bot#5]
Добавить текст приветствия:
` Ассаляму алейкум! Данный бот разработан участниками сообщества <a href="http://it-muslim.com">It Muslim</a> и предназначен для тренировки <a href="http://alfarabinur.kz/arabskiyyazyk/9-urok-spryazhenie-glagolov.html">спряжений арабских глаголов</a>. Участникам предлагается выбирать правильную форму глагола в зависимости от рода, времени и числа. Напишите /start для запуска! `

**Comment by Jihadik** [comment]
The issue is done, we can close it.
